using System.Net.Http.Json;
using System.Text.Json;
namespace CloudClient;
internal static class Program { [STAThread] static void Main(){ApplicationConfiguration.Initialize();Application.Run(new LoginWindow());}}
public sealed class LoginWindow:Form {
 readonly TextBox server=new(){Text="http://localhost:5050",Width=330};readonly TextBox user=new(){PlaceholderText="Benutzername",Width=330};readonly TextBox pass=new(){PlaceholderText="Passwort",UseSystemPasswordChar=true,Width=330};readonly Label state=new(){AutoSize=true};readonly HttpClient http=new();
 public LoginWindow(){Text="i-NET-PROMO Cloudservice";Width=480;Height=430;StartPosition=FormStartPosition.CenterScreen;BackColor=Color.White;var logo=new Label{Text="i-NET-PROMO\nCloudservice",Font=new Font("Segoe UI",24,FontStyle.Bold),AutoSize=true};var login=new Button{Text="Anmelden",Width=330,Height=44};var flow=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,Padding=new Padding(55,45,55,45),WrapContents=false};flow.Controls.Add(logo);flow.Controls.Add(new Label{Text="Serveradresse",AutoSize=true});flow.Controls.Add(server);flow.Controls.Add(new Label{Text="Benutzer",AutoSize=true});flow.Controls.Add(user);flow.Controls.Add(new Label{Text="Passwort",AutoSize=true});flow.Controls.Add(pass);flow.Controls.Add(login);flow.Controls.Add(state);Controls.Add(flow);login.Click+=async(s,e)=>await Login();}
 async Task Login(){try{state.Text="Anmeldung…";var baseUrl=server.Text.TrimEnd('/');var r=await http.PostAsJsonAsync(baseUrl+"/api/login",new{UserName=user.Text,Password=pass.Text});if(!r.IsSuccessStatusCode){state.Text="Anmeldung fehlgeschlagen";return;}var doc=JsonDocument.Parse(await r.Content.ReadAsStringAsync());Hide();new MainWindow(baseUrl,doc.RootElement.GetProperty("displayName").GetString()??user.Text).ShowDialog();Close();}catch(Exception ex){state.Text="Server nicht erreichbar: "+ex.Message;}}
}
public sealed class MainWindow:Form {
 readonly string server;readonly HttpClient http=new();readonly ListView files=new(){Dock=DockStyle.Fill,View=View.Details,FullRowSelect=true};readonly Label title=new(){Dock=DockStyle.Top,Height=62,Font=new Font("Segoe UI",18,FontStyle.Bold),TextAlign=ContentAlignment.MiddleLeft};readonly Label status=new(){Dock=DockStyle.Bottom,Height=28};
 public MainWindow(string url,string name){server=url;Text="i-NET-PROMO Cloudservice";Width=1100;Height=720;MinimumSize=new(850,560);BackColor=Color.FromArgb(247,249,252);title.Text="   Meine Cloud";files.Columns.Add("Name",500);files.Columns.Add("Typ",140);files.Columns.Add("Speicher",160);var nav=new ListBox{Dock=DockStyle.Left,Width=210,Font=new Font("Segoe UI",11),BorderStyle=BorderStyle.None};nav.Items.AddRange(new object[]{"☁  Meine Cloud","▣  Persönlich","▤  Projekte","↗  Mit mir geteilt","⇄  Transfer"});nav.SelectedIndex=0;var top=new Label{Text="Angemeldet als "+name,Dock=DockStyle.Top,Height=34,TextAlign=ContentAlignment.MiddleRight};Controls.Add(files);Controls.Add(title);Controls.Add(status);Controls.Add(nav);Controls.Add(top);Shown+=async(s,e)=>await LoadStorage();}
 async Task LoadStorage(){try{status.Text="Synchronisiere Ansicht…";var data=await http.GetFromJsonAsync<List<Storage>>(server+"/api/storage")??new();files.Items.Clear();foreach(var x in data){var i=new ListViewItem(x.Name);i.SubItems.Add(x.Role);i.SubItems.Add(x.QuotaBytes>0?$"{x.QuotaBytes/1073741824d:N0} GB":"—");files.Items.Add(i);}status.Text="Bereit";}catch(Exception e){status.Text="Fehler: "+e.Message;}}
 sealed class Storage{public string Name{get;set;}="";public string Role{get;set;}="";public long QuotaBytes{get;set;}}
}